sudo: required
services:
    - docker

before_install:
    - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
    #- docker run react-test npm test -- --coverage
    - docker run -e CI=true react-test npm test 

after_success:
    - docker build -t apirutv/multi-client ./client 
    - docker build -t apirutv/multi-nginx ./nginx 
    - docker build -t apirutv/multi-server ./server 
    - docker build -t apirutv/multi-worker ./worker
    # log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push the images to docker hub
    - docker push apirutv/multi-client 
    - docker push apirutv/multi-nginx 
    - docker push apirutv/multi-server
    - docker push apirutv/multi-worker 

deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: DockerReact-env
    bucket_name: elasticbeanstalk-us-east-1-342017321189
    bucker_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY
        


